### ISSUE TITLE
Use Angular to make calls to the API

### ISSUE THREAD

**Issue by jknust** [srobins259/InternetSystemsDevelopment#12]
I noticed that you used AngularJS in classifier.js file but did not use it consistently. I think that it would be beneficial to use angular to make your api calls as well. To do this you would simply create an Angular service that makes requests to the ghdata endpoints and then your Angular controller uses the service to pull in the data to bind to the front end. I think this would give the frontend a more consistent structure and would allow others to better understand what is going on.

**Comment by srobins259** [comment]
We have both so that we could just add onto the ghdata front-end that already existed. Many of the things that we did were far more complicated in the JavaScript they had established, so that is why we added the Angular app on top.
