### ISSUE TITLE
Install/Use:  Ambiguity in Directions

### ISSUE THREAD

**Issue by kalepeterson** [srobins259/InternetSystemsDevelopment#2]
I found a couple spots in the installation process where I think you could lose people who are trying to install.
* Step 1 isn't specific enough in my opinion.  Could you spell out what is meant by "your server solution's web serving"?  Also, by "Clone" I'm guessing you mean downloading the zip file of this repo, not actually cloning it with git right?  (Also, not to nitpick, but there's a typo in "ropository" ;)
* I know you link to OSSHealth/ghdata a lot, but Step 2 should really link as directly to the install instructions as possible.
* Are steps 3 and 4 the same thing, or am I missing something?  I was able to basically ignore them by running "python server.py".  Could you explain what is meant by these steps more?

I was able to get the UI up and running pretty easily since I had a lot of experience with working on a fork of ghdata for our project, but I think that cleaning up these pieces would help out newcomers a lot.

**Comment by jknust** [comment]
I agree with you that installation directions could use some work. I felt like the directions linked away from your repository too much. The more places a user has to go for the installation direction, the more likely they are to get confused or have issues. Plus if your repository does not stay in-sync with OSSHealth the installation instructions their might not work at all.

**Comment by srobins259** [comment]
We have changed it so that the user will just follow instructions for the ghdata version that is running right now, and that we know already works with our front-end.
