### ISSUE TITLE
Code Base:  Making Color Coding More Generic / Reusable

### ISSUE THREAD

**Issue by kalepeterson** [srobins259/InternetSystemsDevelopment#4]
The [classifier.js](https://github.com/srobins259/InternetSystemsDevelopment/blob/master/frontend/scripts/classifier.js) file is nice, but I was wondering if you could refactor it so that there is one function that executes something like `$scope.{metric name}Style.colorClass = {color};`?  That way, the specific functions only have to make a call to that one function instead of writing that line every time.  For example, `commitsGreen` would now be something like `return setColorClass("commits", "green");` 
This could make adding new metrics to the page slightly less painful, and I'm sure there is an even better way to make this code more scalable, but this was just something I noticed.

**Comment by srobins259** [comment]
That is a great recommendation! I will definitely have to look into that more. I was just not incredibly familiar with ajax when I first made the file, so I had to do it the inefficient way.

**Comment by srobins259** [comment]
We finally figure it out and were able to get our functions down to two instead of fifteen. Thanks for the suggestion.
