### ISSUE TITLE
Merge with new ghdata

### ISSUE THREAD

**Issue by srobins259** [srobins259/InternetSystemsDevelopment#5]
Finally got the better install of ghdata

Commands are
git clone {repolink}
sudo pip3 install -upgrade .
ghdata
{edit config file}
ghdata

Graphs populated. Moving on to merging content.

**Comment by srobins259** [comment]
Merged content. Button form is working well. Now I just need to update the repo files.

**Comment by VRRobbie** [comment]
Will be testing out this way on Parallels to download and run project.

**Comment by srobins259** [comment]
Problem must have been the install scripts from ghdata did not like to run in the way we had it. If you setup ghdata and then swap static folders with the one in https://github.com/srobins259/ghdata-working.git, it will add the new features.
